# Generated by Django 3.1 on 2020-08-27 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0004_auto_20200827_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='THSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hum', models.FloatField()),
                ('temp', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thsensor', to='components.sensor')),
            ],
        ),
    ]
