# Generated by Django 3.1 on 2020-08-28 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_auto_20200827_2056'),
        ('thsensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thsensor',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thsensor', to='components.sensor'),
        ),
    ]
