# Generated by Django 3.1 on 2020-08-27 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Component',
        ),
    ]
