# Generated by Django 3.1 on 2020-08-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_controller_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='slug_name',
            field=models.SlugField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='slug_name',
            field=models.SlugField(max_length=40, null=True, unique=True),
        ),
    ]
