# Generated by Django 3.1 on 2020-08-24 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thsensor',
            old_name='humidity',
            new_name='hum',
        ),
    ]
