# Generated by Django 3.1 on 2020-08-27 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20200824_2149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='THSensor',
        ),
    ]
